// Copyright (C) 2025 Michael Kazakov. Subject to GNU General Public License version 3.
#pragma once

@class NSString;

namespace nc::ops::localizable {

NSString *BriefOperationViewControllerWaitingInTheQueueTitle();
NSString *GenericErrorDialogCloseTitle();
NSString *GenericErrorDialogAbortTitle();
NSString *GenericErrorDialogSkipTitle();
NSString *GenericErrorDialogSkipAllTitle();
NSString *AttrChangingAlteringFileAttributesTitle();
NSString *AttrChangingFailedToAccessAnItemMessage();
NSString *AttrChangingFailedToPerformChmodMessage();
NSString *AttrChangingFailedToPerformChownMessage();
NSString *AttrChangingFailedToPerformChflagsMessage();
NSString *AttrChangingFailedToPerformSetTimeMessage();
NSString *AttrChangingSingleTitle();
NSString *AttrChangingMultiTitle();
NSString *BatchRenamingFailedToRenameMessage();
NSString *BatchRenamingBatchRenamingTitle();
NSString *BatchRenamingCantRemoveLastItemMessage();
NSString *CompressionFailedToWriteArchiveMessage();
NSString *CompressionFailedToReadFileMessage();
NSString *CompressionFailedToAccessFileMessage();
NSString *CompressionCompressingItemsTitle();
NSString *CompressionCompressingItemTitle();
NSString *CompressionCompressingToTitle();
NSString *CompressionDiaglogCompressItemsToTitle();
NSString *CompressionDiaglogCompressItemToTitle();
NSString *OperationAbortTitle();
NSString *OperationRetryTitle();
NSString *OperationContinueTitle();
NSString *OperationSkipTitle();
NSString *OperationSkipAllTitle();
NSString *OperationOverwriteTitle();
NSString *OperationUnlockTitle();
NSString *StatisticsFormatterVolOfVolPaused();
NSString *StatisticsFormatterVolOfVol();
NSString *StatisticsFormatterVolOfVolEta();
NSString *StatisticsFormatterVolOfVolSpeed();
NSString *StatisticsFormatterVolOfVolSpeedEta();
NSString *CopyingFailedToAccessFileMessage();
NSString *CopyingFailedToOpenDestFileMessage();
NSString *CopyingFailedToReadSourceFileMessage();
NSString *CopyingFailedToReadDestFileMessage();
NSString *CopyingFailedToWriteDestFileMessage();
NSString *CopyingFailedToCreateDirectoryMessage();
NSString *CopyingFailedToDeleteDestFileMessage();
NSString *CopyingChecksumVerificationFailedMessage();
NSString *CopyingFailedToDeleteSourceFileMessage();
NSString *CopyingItemNotDirMessage();
NSString *CopyingCantRenameLockedMessage();
NSString *CopyingCantDeleteLockedMessage();
NSString *CopyingCantOpenLockedMessage();
NSString *CopyingFailedToUnlockMessage();
NSString *CopyingDialogCopyItemsToTitle();
NSString *CopyingDialogCopyItemToTitle();
NSString *CopyingDialogMoveItemsToTitle();
NSString *CopyingDialogMoveItemToTitle();
NSString *CopyingTitleCopyingPrefix();
NSString *CopyingTitleMovingPrefix();
NSString *CopyingTitleSingleSuffix();
NSString *CopyingTitleMultiSuffix();
NSString *CopyingTitlePreparingToCopySingle();
NSString *CopyingTitlePreparingToMoveSingle();
NSString *CopyingTitlePreparingToCopyMulti();
NSString *CopyingTitlePreparingToMoveMulti();
NSString *CopyingTitleVerifyingResult();
NSString *CopyingTitleCleaningUp();
NSString *DeletionFailedToAccessDirectoryMessage();
NSString *DeletionFailedToDeleteFileMessage();
NSString *DeletionFailedToDeleteDirectoryMessage();
NSString *DeletionFailedToMoveToTrashMessage();
NSString *DeletionDeletePermanentlyTitle();
NSString *DeletionCannotDeleteLockedMessage();
NSString *DeletionCannotTrashLockedMessage();
NSString *DeletionUnlockTitle();
NSString *DeletionFailedToUnlockMessage();
NSString *DeletionSingleTitle();
NSString *DeletionMultiTitle();
NSString *DeletionDialogMoveToTrashTitle();
NSString *DeletionDialogDeletePermanentlyTitle();
NSString *DeletionDialogDoYouWantToDeleteSingleMessage();
NSString *DeletionDialogDoYouWantToDeleteMultiMessage();

} // namespace nc::ops::localizable
